version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 5055:5055 # Jellyseer
      - 6767:6767 # Bazarr
    volumes:
      - /home/coomshack/docker/arr-stack:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=ePayj9oAdXohqM68z469Mz/vWqoEoENWbXZxd5lKJkM= # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - WIREGUARD_ADDRESSES=10.70.68.245/32
      # Timezone for accurate log times
      - TZ=Europe/Copenhagen
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - WEBUI_PORT=8085
    volumes:
      - /home/coomshack/docker/arr-stack/qbittorrent:/config
      - /home/coomshack/data/torrents:/data/torrents/
    depends_on:
      - gluetun
    restart: always

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    network_mode: "service:gluetun"
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/coomshack/docker/arr-stack/radarr:/config
      - /home/coomshack/data:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /home/coomshack/docker/arr-stack/sonarr:/config
      - /home/coomshack/data:/data
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    network_mode: "service:gluetun"
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/coomshack/docker/arr-stack/bazarr:/config
      - /home/coomshack/data/media:/data/media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /home/coomshack/data/prowlarr:/config
    restart: unless-stopped

  jellyseerr: 
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    network_mode: "service:gluetun"
    hostname: jellyseerr 
    user: 1000:1000 
    environment: 
      - TZ=Europe/Copenhagen
    ports: 
      - 5055:5055 
    volumes: 
      - /home/coomshack/data/jellyseerr:/app/config 
    restart: unless-stopped 
    depends_on: 
      - sonarr 
      - radarr
